<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Users who read this <strong>{title}</strong>' => '',
    'Access denied!' => 'Доступ запрещён!',
    'Announcement not found!' => 'Анонс не найден!',
    'Could not load Announcement!' => 'Анонс не может быть загружен!',
    'Users didn\'t read this <strong>{title}</strong>' => 'Пользователь не прочитал <strong>{title}</strong>',
    'You have insufficient permissions to perform that operation!' => 'У вас недостаточно прав для выполнения этой операции!',
];
