<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Reset Statistics' => '',
    'Add Announcement...' => 'Добавить Анонс...',
    'Complete Announcement' => 'Завершить Анонс',
    'Mark as read' => 'Отметить прочитанным',
    'Mark as unread' => 'Отметить непрочитанным',
    'Note: You can use markdown syntax. (For more information visit <a target="_blank" href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet">this link</a>)' => 'Примечание: Вы можете использовать markdown синтаксис. (Для большей информации посетите <a target="_blank" href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet">эту ссылку</a>)',
    'Old' => 'Устарел',
    'Read, ' => 'Прочитали,',
    'Reopen Announcement' => 'Перевыпустить анонс',
    'Statistic:' => 'Статистика:',
    'Unread' => 'Непрочитали',
    'and {count} more didn\'t read this.' => 'и более {count} непрочитали это.',
    'and {count} more read this.' => 'и более {count} прочитали это.',
];
