<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
 
return [
    '<strong>Announcement</strong> module configuration' => 'Paramètres du module <strong>annonces</strong>',
    'Global settings' => 'Paramètres Généraux',
    'Notify all Space Members if an announcement has been closed or reopened.' => 'Avertir les membres lorsqu\'une annonce est clôturée ou réouverte.',
    'Notify all Space Members if an announcement has been created.' => 'Avertir les membres lorsqu\'une annonce est créée.',
    'Notify all Space Members if an announcement has been updated.' => 'Avertir les membres lorsqu\'une annonce est mise à jour.',
    'Notify all Space Members if an announcement statistics has been reset.' => 'Avenir les membres lorsque les statisques d\'une annonce sont remises à zéro.',
];
