<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Announcement...' => 'Publier une annonce importante...',
    'Complete Announcement' => 'Compléter l‘annonce',
    'Mark as read' => 'Marquer comme lu',
    'Mark as unread' => 'Marquer comme non lu',
    'Note: You can use markdown syntax. (For more information visit <a target="_blank" href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet">this link</a>)' => 'Note : vous pouvez utiliser la syntaxe markdown. (Pour plus d‘informations, consultez <a target="_blank" href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet">ce lien</a>)',
    'Old' => 'Ancien',
    'Read, ' => 'Lu(s)',
    'Reopen Announcement' => 'Réouvrir l‘annonce',
    'Statistic:' => 'Statistiques',
    'Unread' => 'Non lu(s)',
    'and {count} more didn\'t read this.' => 'et {count} autres non lus',
    'and {count} more read this.' => 'et {count} autres à lire',
];
