<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Announcement...' => 'Ankündigung hinzufügen...',
    'Complete Announcement' => 'Ankündigung schliessen',
    'Mark as read' => 'Als gelesen markieren',
    'Mark as unread' => 'Als ungelesen markieren',
    'Note: You can use markdown syntax. (For more information visit <a target="_blank" href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet">this link</a>)' => 'Hinweis: Du kannst die Markdown Sytax verwenden. (Weitere Infos unter <a target="_blank" href="http://www.markdown.de">diesem Link</a>)',
    'Old' => 'Veraltet',
    'Read, ' => 'Gelesen, ',
    'Reopen Announcement' => 'Ankündigung wieder öffnen',
    'Statistic:' => 'Auswertung:',
    'Unread' => 'Nicht gelesen',
    'and {count} more didn\'t read this.' => 'und {count} mehr haben das nicht gelesen.',
    'and {count} more read this.' => 'und {count} mehr haben das gelesen.',
];
