<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Announcement...' => '',
    'Complete Announcement' => '',
    'Mark as read' => '',
    'Mark as unread' => '',
    'Note: You can use markdown syntax. (For more information visit <a target="_blank" href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet">this link</a>)' => '',
    'Old' => '',
    'Read, ' => '',
    'Reopen Announcement' => '',
    'Statistic:' => '',
    'Unread' => '',
    'and {count} more didn\'t read this.' => '',
    'and {count} more read this.' => '',
];
